package com.pazim.bankbudget;
import android.app.*;import android.content.*;import android.os.Bundle;import android.provider.Settings;import android.text.InputType;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity {
 private final NumberFormat money=NumberFormat.getCurrencyInstance(Locale.CANADA);private LinearLayout dashboard,list;private TextView total;private long start,end;
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
 @Override protected void onResume(){super.onResume();refresh();}
 private void build(){
  ScrollView sv=new ScrollView(this);LinearLayout root=v();root.setPadding(dp(18),dp(18),dp(18),dp(30));sv.addView(root);
  TextView title=t("Bank Budget Tracker",28);root.addView(title);
  TextView p=t("All detected transactions remain on this phone. Enable notification access, then bank and Google Wallet transaction notifications will be analyzed automatically.",14);p.setPadding(0,dp(7),0,dp(12));root.addView(p);
  Button access=b("Enable notification access");access.setOnClickListener(x->{try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Exception e){Toast.makeText(this,"Open Settings and search Notification access",Toast.LENGTH_LONG).show();}});root.addView(access);
  Button manual=b("Add transaction manually");manual.setOnClickListener(x->transactionDialog(null));root.addView(manual);
  Button category=b("Add category");category.setOnClickListener(x->addCategory());root.addView(category);
  total=t("",22);total.setPadding(0,dp(18),0,dp(6));root.addView(total);root.addView(t("Category budgets",20));dashboard=v();root.addView(dashboard);
  TextView th=t("Transactions",20);th.setPadding(0,dp(18),0,dp(6));root.addView(th);list=v();root.addView(list);
  Button refresh=b("Refresh");refresh.setOnClickListener(x->refresh());root.addView(refresh);setContentView(sv);
 }
 private void refresh(){
  range();BudgetDatabase db=BudgetDatabase.get(this);List<String> cats=db.getCategories();List<Transaction> txs=db.getTransactions(start,end);double sum=0;for(Transaction x:txs)if("DEBIT".equals(x.type))sum+=x.amount;total.setText("This month: "+money.format(sum));
  dashboard.removeAllViews();for(String c:cats){if("Income".equals(c)||"Transfers".equals(c))continue;double spent=db.monthSpending(c,start,end),budget=db.getBudget(c);Button row=b(c+": "+money.format(spent)+(budget>0?" / "+money.format(budget):" / no budget"));row.setAllCaps(false);row.setOnClickListener(x->budgetDialog(c,budget));dashboard.addView(row);}
  list.removeAllViews();if(txs.isEmpty())list.addView(t("No transactions detected this month.",15));else{SimpleDateFormat d=new SimpleDateFormat("MMM d, h:mm a",Locale.CANADA);for(Transaction x:txs){Button item=b(("CREDIT".equals(x.type)?"+":"-")+money.format(x.amount)+" • "+x.merchant+"\n"+x.category+" • "+x.source+" • "+d.format(x.timestamp));item.setAllCaps(false);item.setOnClickListener(y->transactionDialog(x));list.addView(item);}}
 }
 private void transactionDialog(Transaction old){
  BudgetDatabase db=BudgetDatabase.get(this);LinearLayout form=v();form.setPadding(dp(18),dp(4),dp(18),0);EditText amount=input("Amount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL),merchant=input("Merchant or description",InputType.TYPE_CLASS_TEXT);Spinner cat=spinner(db.getCategories()),type=spinner(Arrays.asList("DEBIT","CREDIT","TRANSFER"));CheckBox remember=new CheckBox(this);remember.setText("Remember this merchant category");form.addView(amount);form.addView(merchant);form.addView(cat);form.addView(type);form.addView(remember);
  if(old!=null){amount.setText(String.valueOf(old.amount));merchant.setText(old.merchant);select(cat,old.category);select(type,old.type);}
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(old==null?"Add transaction":"Edit transaction").setView(form).setPositiveButton("Save",null).setNegativeButton("Cancel",null).setNeutralButton(old==null?null:"Delete",null).create();
  dialog.setOnShowListener(z->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{double a;try{a=Double.parseDouble(amount.getText().toString().trim());}catch(Exception e){amount.setError("Enter a valid amount");return;}String m=merchant.getText().toString().trim();if(m.isEmpty()){merchant.setError("Enter a merchant");return;}String c=String.valueOf(cat.getSelectedItem()),ty=String.valueOf(type.getSelectedItem());if(old==null){Transaction n=new Transaction();n.timestamp=System.currentTimeMillis();n.amount=a;n.currency="CAD";n.merchant=m;n.category=c;n.source="Manual";n.type=ty;n.rawText="Manually added";n.manual=true;n.fingerprint="manual-"+System.nanoTime();db.insertTransaction(n);if(remember.isChecked())db.saveMerchantRule(m,c);}else db.updateTransaction(old.id,a,m,c,ty,remember.isChecked());dialog.dismiss();refresh();});if(old!=null)dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(x->{db.deleteTransaction(old.id);dialog.dismiss();refresh();});});dialog.show();
 }
 private void addCategory(){EditText x=input("Category name",InputType.TYPE_CLASS_TEXT);new AlertDialog.Builder(this).setTitle("Add category").setView(x).setPositiveButton("Add",(d,w)->{BudgetDatabase.get(this).addCategory(x.getText().toString());refresh();}).setNegativeButton("Cancel",null).show();}
 private void budgetDialog(String c,double current){EditText x=input("Monthly budget for "+c,InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(current>0)x.setText(String.valueOf(current));new AlertDialog.Builder(this).setTitle(c+" budget").setView(x).setPositiveButton("Save",(d,w)->{try{BudgetDatabase.get(this).setBudget(c,Double.parseDouble(x.getText().toString().trim()));refresh();}catch(Exception e){Toast.makeText(this,"Invalid budget",Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancel",null).show();}
 private void range(){Calendar s=Calendar.getInstance();s.set(Calendar.DAY_OF_MONTH,1);s.set(Calendar.HOUR_OF_DAY,0);s.set(Calendar.MINUTE,0);s.set(Calendar.SECOND,0);s.set(Calendar.MILLISECOND,0);start=s.getTimeInMillis();Calendar e=(Calendar)s.clone();e.add(Calendar.MONTH,1);e.add(Calendar.MILLISECOND,-1);end=e.getTimeInMillis();}
 private LinearLayout v(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;}private TextView t(String s,float z){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);return x;}private Button b(String s){Button x=new Button(this);x.setText(s);return x;}private EditText input(String h,int type){EditText x=new EditText(this);x.setHint(h);x.setInputType(type);x.setPadding(dp(8),dp(8),dp(8),dp(8));return x;}private Spinner spinner(List<String> v){Spinner x=new Spinner(this);x.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,v));return x;}private void select(Spinner s,String v){for(int i=0;i<s.getCount();i++)if(v.equals(String.valueOf(s.getItemAtPosition(i)))){s.setSelection(i);return;}}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
}
